---
title: "Open Payments Guide"
author: "Quinn White"
date: "1/5/2022"
output: 
  rmdformats::readthedown:
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

### Overview

The Open Payments data set contains records of payments made by drug and medical device companies to physicians, non-physician practitioners (NPPs), and teaching hospitals. It was created by the Centers for Medicare and Medicaid Services to meet the criteria established in the [Physician Payment Sunshine Act](https://www.advamed.org/legal/physician-payments-sunshine-act/). This act aims to increase the transparency in the United States healthcare system by publicly documenting financial ties between medical practitioners or facilities and drug and device companies. These ties have been extremely prevalent for over a decade: a survey conducted in 2009 using a stratified random sample of primary care providers and specialists revealed the percentage of physicians with any type of industry relationship was 84% ([Source](https://jamanetwork.com/journals/jamainternalmedicine/fullarticle/226207)). Beyond transparency, mandating disclosure is intended to discourage inappropriate relationships and provide a system of accountability ([Source](https://www.cms.gov/files/document/open-payments-user-guide-reporting-entities.pdf)).

### Details on the Production of the Data

Reporting entities include applicable manufacturers as well as group purchasing organizations, which are implicated in the sale of a covered product and must meet some additional criteria ([Source](https://www.cms.gov/OpenPayments/Program-Participants/Reporting-Entities)). This definition encapsulates entities arranging pharmaceutical contracts not exclusively for the entity itself, as well as physician-owned distributors of medical devices. 

All covered products must be reimbursed by Medicare, Medicaid, or the Children’s Health Insurance Program (CHIP) ([Source](https://www.cms.gov/OpenPayments/Program-Participants/Reporting-Entities)). For a  drug or biological to be covered, it must require a prescription or doctor’s authorization to be given. For a device or medical supply to be covered, it must require premarket approval or premarket notification by the FDA.

 By law, these reporting entities must disclose any transfers of value they make to covered recipients, which, as of January 2021, includes physicians, teaching hospitals, physician assistants, nurse practitioners, clinical nurse specialists, certified registered nurse anesthetists, anesthesiologist assistants, and certified nurse-midwives. The 2021 criteria for covered recipients represents a change from previous years in the expansion to include non-physician providers ([Source](https://openpaymentsdata.cms.gov/about/glossary)). 

The data submission process occurs online. To submit their transfers of value, reporting entities must log into a [portal](https://portal.cms.gov/portal/) where they can fill out the required information. Extensive documentation is available to reporting entities, including a 375 page [user guide](https://www.cms.gov/files/document/open-payments-user-guide-reporting-entities.pdf) that provides background on the program and its intentions as well as the technical details of filling out the form. 

e Drug Name and National Drug Code (NDC) Reference Data is a reference tool for Applicable Manufacturers and Applicable Group Purchasing Organizations (GPOs),

Transfers of value can take a variety of forms ([Source](https://www.advamed.org/legal/physician-payments-sunshine-act/)). Consulting fees are common due to the need for medical expertise in the development of medical products to ensure these products are beneficial in clinical settings, and honoraria are often paid when a medical practitioner shares their expertise at a conference. A central form of financial ties is through research grants and payments, where medical providers are compensated for their role in the research and development process, which is generally time intensive. Education on the utilization of a newly developed device is another transfer of value, and is often required by the FDA. Beyond training, providers may participate in events designed to teach others about the device or contribute to educational materials on the device. Additionally, providers acting as innovators also may be granted royalties to compensate them for their product development ideas. These examples are a subset of all possible transfers of values, but demonstrate the extent to which financial ties are woven into our medical infrastructure in the United States.
 
These transfers of value are collected throughout the entire calendar year, and then data from the previous year must be submitted by reporting entities between February 1st and March 31st ([Source](https://www.cms.gov/openpayments)). Data review occurs from April 1st to May 30th; covered recipients have the opportunity to review payments related to them before the data is made public, but although this review is encouraged, it is not mandatory. The Centers for Medicare & Medicaid services does not mediate disputes, so it is up to the covered recipient and reporting entity to come to a resolution ([Source](https://www.cms.gov/files/document/physician-and-teaching-hospital-review-and-dispute-tutorial.pdf)). If the dispute is resolved in the review period, the corrected data will be published in the initial publication, but if the dispute is not resolved in this time frame, the transaction is marked as disputed in the initial publication. Corrections made after the review period are not visible in the initial publication but are made available the following year. The data are released to the public by the Centers for Medicare & Medicaid services (accessible at OpenPaymentsData.cms.gov) for the initial publication by June 30th.



### Prevalence & Impact of Industry Ties 

In many ways, the Sunshine Act has represented a much needed shift toward greater transparency ([Source](https://www.statnews.com/2017/01/25/sunshine-act-physicians-conflict-of-interest/)) Historically, relying on medical providers to disclose potential conflicts of interest in medical journal articles has not been effective. To look at compliance with financial disclosures in medical papers, one study looked at payments made by several orthopedic device companies device companies to their consultants in 2007, before the implementation of the Open Payments System ([Source](https://jamanetwork.com/journals/jamainternalmedicine/fullarticle/226394)). 
A financial interest was disclosed in less than half of papers with a co-author receiving a million or more from one of the analyzed device companies. Of note, failing to disclose these financial conflicts of interest goes against the policies upheld by many of the medical journals included. 

Additionally, industry ties related to those writing clinical guidelines is a particularly notable conflict of interest given the impact these guidelines have on the care patients receive. These  conflicts of interests have been shown to be pervasive across various fields. In psychiatry, concern has been raised over financial ties between panel members contributing to the Diagnostic and Statistical Manual of Mental Disorders ([Source](https://www-karger-com.libproxy.smith.edu/Article/FullText/357499)).  Of particular interest here are the cases where panel members responsible for decisions regarding the inclusion of new disorders are tied to companies involved in clinical trials to treat those specific disorders. The results showed that over a quarter of work group members (who focus on a specific diagnostic category) and over 60% of task force members (who oversee the entire manual) reported at least one conflict of interest to a trial drug manufacturer.

Meanwhile, one study assessing panel members who develop clinical guidelines for diabetes and hyperlipidaemia found a high prevalence of financial conflicts of interest, with prevalence differing depending on whether the panels were sponsored by government or by other entities ([Source](https://www.bmj.com/content/343/bmj.d5621)). Work evaluating authors of  guidelines published by the American Academy of Dermatology using the Open Payments database showed that over 80% received at least 1 reported industry payment, and over half had accepted more than \$10,000 ([Source](https://jamanetwork-com.libproxy.smith.edu/journals/jamadermatology/fullarticle/2657683)). Comparing the disclosure statements for the guidelines to the information obtained from the Open Payments data revealed frequent discrepancies, indicating a lack of enforcement of the journal’s disclosure requirements. In a more comprehensive study of clinical guidelines spanning various disciplines, the Open Payments data revealed that on average, a group panel member received \$19,972, and the median payment was $1,227; these payments were not always accurately disclosed ([Source](https://www-sciencedirect-com.libproxy.smith.edu/science/article/pii/S1865921720300477?via%3Dihub)).  


Although [concerns have been raised](https://www.healthaffairs.org/do/10.1377/hpb20141002.272302/full/) about the Sunshine Act impeding industry ties, a ProPublica analysis found that industry spending has been at a consistent level from 2014 to 2018 ([Source](https://www.propublica.org/article/we-found-over-700-doctors-who-were-paid-more-than-a-million-dollars-by-drug-and-medical-device-companies)). 

There are also important concerns regarding the impact of industry ties on ramping up health care costs. One study found a dose dependent relationship between the meals a physician received that were sponsored by a drug company and the rate at which the physician prescribed that drug ([Source](https://jamanetwork.com/journals/jamainternalmedicine/article-abstract/2528290)). That is, more meals paid for by the drug company, and more costly meals, were associated with higher prescription rates of that drug. Because this work was cross-sectional and identified associations, there is a need for more studies evaluating whether there is a causal link between industry-sponsored meals and prescribing rates as well as other forms of industry ties. Findings like this challenge the perception that industry ties of small scale are benign, and emphasizes the potential they have to shape the quality and cost of care that patients receive.

ProPublica found a similar trend in analysis of data from the Open Payments system in 2014, with higher amounts of money received from drug or device companies being associated with higher brand-name prescribing rates ([Source](https://www.propublica.org/article/doctors-who-take-company-cash-tend-to-prescribe-more-brand-name-drugs)). This is notable since generic options are less aggressively marketed but much more affordable, despite showing similar rates of efficacy compared to name brand drugs ([Source](https://www.fda.gov/drugs/generic-drugs/generic-drug-facts)). A later ProPublica analysis found that the types of drugs most promoted to providers were in markets with high competition, often where other available drugs work with a similar mechanism  ([Source](https://www.propublica.org/article/we-found-over-700-doctors-who-were-paid-more-than-a-million-dollars-by-drug-and-medical-device-companies)). Again, this raises the question of whether patients are prescribed drugs that is less affordable than alternatives due to their provider’s industry ties. 

A central question regarding industry ties is how they impact research. One Cochrane review of studies on the association between sponsorship and research outcome found that the industry sponsored studies tended to show more favorable efficacy results ([Source](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8132492/)). 

### Limitations of the Open Payments Program 

Despite that the Open Payments program provides useful information on conflicts of interest related to provider-industry ties, some conflicts of interest remain untracked. For example, the phenomenon of self-referral, where a medical provider refers their patients to a facility for which they, or a family member, have a financial interest, has been called into question as a factor contributing to rising health care costs. A report by the United States Government Accountability Office on anatomic pathology – the study of tissue samples to diagnose conditions –  that examined data from 2004 to 2010 found that self-referred services increased at a faster rate compared to non-self-referred services, and that the expenditures for self-referred services increased at a higher rate than non-self-referred services  ([Source](https://www.gao.gov/assets/gao-13-445-highlights.pdf)). Notably, providers beginning self-referral services showed increased referred anatomic pathology services compared to the period before self-referring, whereas providers that had no change in self-referral habits had lower changes in utilization of anatomic pathology services, which indicates the increase in anatomic pathology referrals among those beginning to self-refer could not be explained by a general increase in the use of these services. 

Since then, the Centers for Medicare & Medicaid Services initiated a change in self-referral regulations modifying the Section 1877 of the Social Security Act to reduce “undue regulatory impact and burden of the physician self-referral law” ([Source](https://www.federalregister.gov/documents/2020/12/02/2020-26140/medicare-program-modernizing-and-clarifying-the-physician-self-referral-regulations)). However, information on self-referral is generally difficult to study given that actual or potential violations are self-reported through the CMS Voluntary Self-Referral Disclosure Protocol ([Source](https://www.cms.gov/Medicare/Fraud-and-Abuse/PhysicianSelfReferral/Self_Referral_Disclosure_Protocol)). Therefore, we see that Open Payments increases the transparency regarding provider-industry ties, but does not put forth a comprehensive view of conflicts of interests within the health care system. 

Technical issues also may arise when looking at this data. Several variables are input via free text, which means misspellings can and do occur. In one year, Forest Laboratories misspelled the depression drug Fetzima 953 times, which ended up being over a third of the total reports on the drug ([Source](https://www.propublica.org/article/why-pharma-payments-to-doctors-were-so-hard-to-parse)).  Multiple reports on a single drug also used different names , which makes the payments associated with the drug appear less substantial than they really are ([Source](https://www.propublica.org/article/why-pharma-payments-to-doctors-were-so-hard-to-parse)). These errors may not be deliberate, but they still make it harder to glean meaning from the data, even when it is publicly available. 


### Transparency and Trust

As we think about the impact of the Open Payments program, it is important to evaluate not only the information now available about industry-provider ties, but also the effect on the perceptions and knowledge of the public. This is particularly relevant because the public’s perceptions about their own providers can have implications for how they respond to their providers’ recommendations ([Source](https://pubmed.ncbi.nlm.nih.gov/23027114/)). The relationship between public trust and available information is nuanced, as is the relationship between public knowledge and trust; more information does not always correlate to greater trust. Indeed, the results of surveys as well as experimental work on how trust relates to financial disclosures provides some more information on the complexities underlying this relationship.  


For one, people’s beliefs about conflicts of interest, whether or not they do indeed exist, may shape their trust. In one survey, believing that their physician receives industry gifts was associated with low physician trust and high distrust in the health care system, and the broader perception that almost all doctors accept gifts was also associated with low physician trust and high distrust in the health care system ([Source](https://link-springer-com.libproxy.smith.edu/article/10.1007%2Fs11606-011-1760-3)).  
One randomized experiment supports this relationship between perceived conflicts of interest and trust: increasing industry payments to physicians were associated with lower patient ratings for honesty and fidelity ([Source](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5653550/)). That said, industry payments to physicians were not associated with a difference in competency ratings. This implies that deciphering what it means to trust one’s physician is somewhat ambiguous: if someone believes their physician is dishonest but competent, the resulting impact on their interactions is unclear. Notably, no significant differences were observed between the ‘Disclosure’ and ‘No Disclosure’ arms for any measure of trust for the medical profession. This conflict with the previous study could be explained by multiple phenomena. First, the first was observational, studying beliefs about industry payments, whereas the second was evaluating the effect of an intervention, the exposure to disclosure information. This means the first study may have been observing that suspicion of industry gifts tends to be associated with low trust in physicians and the medical system, regardless of whether these industry gifts are explicitly disclosed or believed to exist. However, disclosure may impact this group in notable ways as well. This survey study was conducted on individuals across 40 large metropolitan areas, while the randomized trial consisted solely of individuals residing in Massachusetts. Distinctions in attitudes across the samples may also contribute to this disparity.  


 
When considering the impact of disclosures, we must recognize that the impact of disclosure on a patient may depend on the information disclosed. If the disclosure is informative rather than concerning, patients may have little change in confidence in their provider. Indeed, this was observed in a randomized trial evaluating the effect of sending a letter to patients explaining the compensation system at the group where their physician practiced ([Source](https://jamanetwork.com/journals/jamainternalmedicine/fullarticle/410044)).  Over 70% of respondents reported that the intervention did not change their level of trust in their primary care physician, and over a fifth responded that the disclosure had increased trust to some degree. However, there is also the fact that patients may not be aware of how industry ties may impact the care they receive. A randomized experiment of patients who had appointments with physicians paid more than $20,000 by industry the previous year found that disclosing this information in the form of a letter improved their knowledge of this financial conflict of interest but did not change their level of trust in their physician ([Source](https://www-sciencedirect-com.libproxy.smith.edu/science/article/pii/S0749597818304709?via%3Dihub)). Patients may not be accustomed to thinking about conflict of interest data as they interact with the medical system; without education on how to interpret this data, their ability to benefit from it is highly limited. 

Of note, the utilization of the Open Payments system for personal purposes is very low. One cross-sectional survey found that although the majority of respondents had seen a physician who received an industry payment, only 12% were aware that this information was publicly available, and only 5% were aware of whether their provider had received any payments ([Source](https://link-springer-com.libproxy.smith.edu/article/10.1007%2Fs11606-017-4012-3)). A longitudinal survey recording responses prior to the public disclosure of payments in September 2014, prior to the public disclosure of payments, and again 2 years later, after the public disclosure of payments, showed that there was no significant change in knowledge of whether their own doctor had received payments from industry ([Source](https://bmjopen.bmj.com/content/9/2/e024020.abstract)). However, despite the low level of awareness, there was a reduced level of trust in their physician within this time period, whether or not they knew if their physician had received any transfers of value ([Source](https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2730473?utm_source=TrendMD&utm_medium=cpc&utm_campaign=JAMA_Network_Open_TrendMD_1)).  There was also a reduced trust in the medical profession overall ([Source](https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2730473?utm_source=TrendMD&utm_medium=cpc&utm_campaign=JAMA_Network_Open_TrendMD_1)). 

This work underscores the essential nature of communication around how we interpret datasets like that generated by the Open Payments program. A general reduction in the trust in medical providers is not in the interest of public health, but informing individuals on how they can advocate for themselves and family members to obtain high quality and cost effective care amidst a health care system entangled in industry ties remains crucial. Making this distinction may lie in part in the difference between broad-scale systemic information (such as the prevalence of industry ties across the system) and patient-level information (such as the payments received by the providers a patient is seeing). Media coverage tends to focus on the former. Still, engaging with this data at the patient level may provide better assistance to individuals navigating the healthcare system rather than looking at higher level trends and being discouraged by the pervasiveness of financial conflicts of interest across the country. 

As we see in the case of Open Payments, transparency in itself does not create a just medical system. That transparency must be coupled with effective communication on how to interpret the information that is now readily available to anyone with an internet connection. 
 Transfers of value encapsulate a broad range of transactions, and the nature of these transactions is important when evaluating conflicts of interest. Additionally, for patients to benefit from this data, they should look at records for their specific providers rather than the broader trends. 




### Background 

*  website is managed and paid for by the U.S. Centers for Medicare & Medicaid Services  
*  open payments program expansion --
    * as of January 1, 2021, reporting entities required to report payments made to physicians and teaching hospitals as well as:
        * physician assistant
        * nurse practitioners
        *clinical nurse specialists
        *certified registered nurse anesthetists
        *anesthesiologist assistants
        * certified nurse-midwives
* [about the program](https://openpaymentsdata.cms.gov/about)
    * transparency program to elucidate financial relationships between drug/device companies (reporting entities) and health care providers (covered recipients)
    * aims to add transparency to health care system 
[terms](https://www.ecfr.gov/current/title-42/chapter-IV/subchapter-A/part-403/subpart-I) 
    * covered recipients = physicians (excluding medical residents) who are not employees of manufacturer reporting the payment, teaching hospitals that receive payment for Medicare direct graduate medical education (GME), inpatient prospective payment system (IPPS) indirect medical education (IME)
    * psychiatric hospital IME programs 
    * types of payments
         * Charitable contributions
         * Consulting fees
         * Compensation for services other than consulting, including serving as faculty or as a speaker at an event other than a continuing education program
         * Honoraria
         * Gifts
         * Entertainment
         * Food and beverage
         * Travel and lodging
         * Education
         * Research
         * Royalty or license
         * Current or prospective ownership or investment interest
         * Compensation for serving as faculty or as a speaker for an          unaccredited and non-certified continuing education program
         * Compensation for serving as faculty or as a speaker for an accredited or certified continuing education program
         * Grants
         * Space rental or facility fees (teaching hospital only)
    * applicable group purchasing organization (GPO)   
        * “entities that operate in the United States and purchase, arrange for or negotiate the purchase of covered drugs, devices, biologicals, or medical supplies for a group of individuals or entities, but not solely for use by the entity itself”
    * applicable manufacturers
        * engaged in the production, preparation, propagation, compounding, or conversion of a covered drug, device, biological, or medical supply, but not if such covered drug, device, biological or medical supply is solely for use by or within the entity itself or by the entity's own patients (this definition does not include distributors or wholesalers (including, but not limited to, repackagers, relabelers, and kit assemblers) that do not hold title to any covered drug, device, biological or medical supply)
        * entities under common ownership with entity meeting the above criteria
    * national provider identifier (NPI)
        * unique identification number for covered health care providers 
10 digit 
    * newly added covered recipients
        * as of Jan 2021,  physician assistants, nurse practitioners, clinical nurse specialists, certified registered nurse anesthetists & anesthesiologist assistants, and certified nurse-midwives are now included 
non-physician practitioner covered recipient
providers practicing in collaboration with or under supervision of physician
        * non-physician practitioners = NPPs
    * ownership or investment interest
        * includes (but not limited to): stock, partnership shares, limited liability company memberships, loans, bonds
    * physician
         * includes:
            * Doctors of Medicine or Osteopathic Medicine
            * Doctors of Dental Medicine or Dental Surgery
            * Doctors of Podiatric Medicine
            * Doctors of Optometry
            * Chiropractors
        * medical residents excluded 
    * reporting entities
        * applicable manufacturers or applicable GPOs 
    * teaching hospital 
        * hospitals that receive payment for any of:
            * Medicare direct graduate medical education (GME)
            *  IPPS indirect medical education (IME)
            *  psychiatric hospital IME programs
    * covered products
        * Reimbursed by Medicare, Medicaid, or Children’s Health
Insurance Program AND the product is a drug or biological, and it requires a prescription (or doctor’s authorization) to administer 
        * OR the product is a device or medical supply, and it requires premarket approval or premarket notification by the FDA
* [Timeline](https://www.cms.gov/openpayments)
    * data collection: all year (Jan 1 - Dec 31)
        * reporting entities record payments made to covered recipients
    * data submission: Feb 1 - March 31
        * reporting entities submit the recorded data from the previous year 
    * data review: Apr 1 - May 30
        * covered recipients can review the submitted data related to them and initiate a dispute if necessary (but CMS does not mediate disputes)
this review and dispute process is optional; covered recipients may choose to not review the data 
    * data publication: on or by June 30th
        * CMS releases the data, available at OpenPaymentsData.cms.gov

